### ISSUE TITLE
xattr.Setxattr triggers an error with (errno 0) code

### ISSUE THREAD

**Issue by bexp** [pkg/xattr#10]
I have go program which utilizes xattr lib and it gives me fake errors while writing xattr

```
func writeXattr(path, name string, data []byte, l log15.Logger) {
	err := xattr.Setxattr(path, name, data)

	if err != nil {
		l.Error("Setxattr failed", "err", err, "name", name, "path", path)
	}
}
```
example of log message 
EROR[03-24|15:27:52] Setxattr failed                          module=tests url=http://curl.haxx.se/rfc/rfc1635.txt uuid_low=983ca2a62a257759 file=/tmp/pztest/0e/0e319b3e1d23aef6458258df630b92b0 err="setxatt
r /tmp/pztest/0e/0e319b3e1d23aef6458258df630b92b0_part user.h.Server: errno 0" name=user.h.Server path=/tmp/pztest/0e/0e319b3e1d23aef6458258df630b92b0_part

File itself contains all xattrs which I set. So I had to come up with following workaround to prevent 
those non-existent errors to pollute my logs:

```
func writeXattr(path, name string, data []byte, l log15.Logger) {
	err, ok := xattr.Setxattr(path, name, data).(*xattr.XAttrError)
	if ok && err.Err.(syscall.Errno) != 0 {
		l.Error("Setxattr failed", "err", err, "name", name, "path", path)
	}
}
```

**Comment by kuba--** [comment]
@bexp can you give more details:
- what OS?
- which commit do you use (did you try the latest version or master)?

**Comment by bexp** [comment]
yes I don't see this happening with latest version, I used pretty old one from last year

**Comment by kuba--** [comment]
yeah, it was fixed, recently

**Comment by kuba--** [comment]
@bexp I'm closing this issue, because it's already fixed in latest version.
