### ISSUE TITLE
test fails: "operation not supported"

### ISSUE THREAD

**Issue by legrostdg** [pkg/xattr#11]
I'm trying to package `xattr` for Debian. The tests fail with:

    go test -v -p 4 github.com/pkg/xattr
    === RUN   Test
    --- FAIL: Test (0.00s)
	    xattr_test.go:23: xattr.Set /tmp/179974020 user.test: operation not supported
    FAIL

**Comment by davecheney** [comment]
How is your /tmp mounted. Does the test pass if you set TMPDIR to another
location, probably in your home directory?

**Comment by legrostdg** [comment]
I'm working in a chroot, which apparently has user_xattr disabled. Would it be possible to add a check to see if user_xattr is disabled, and if so, try this again on the current directory, and if it is disabled too, skip the tests?

**Comment by legrostdg** [comment]
I also tried to set TMPDIR to another location, but TMPDIR is used in other places in the package building... That does not seem to interact very well.

**Comment by davecheney** [comment]
I'm not sure how hard it would be to add that check. I'm not even sure
where to start. Smells like it might require a check at the start of the
test and some kind of probing of the error value returned.

**Comment by legrostdg** [comment]
Maybe by checking if the mount points in /proc/mounts contain user_xattr? It may be kind of dirty but I did not find something better...

Something like this with user_xattr instead of acl: https://stackoverflow.com/questions/6291985/how-to-check-wheter-posix-acl-is-enabled-for-a-given-path

Otherwise I guess I'll have to disable the tests when building the package.

**Comment by kuba--** [comment]
how about temporary workaround and check if we got `operation not supported` error?

**Comment by kuba--** [comment]
@legrostdg, @davecheney - how about implementing something similar to:
https://github.com/snowyu/xattr.php/blob/master/xattr.c#L227

**Comment by kuba--** [comment]
@legrostdg - I've sent a PR (https://github.com/pkg/xattr/pull/14) adding `xattr.Supported` function, so please take a look if it works for you. I'm also skipping tests if OS. doesn't support xattr.

**Comment by kuba--** [comment]
PR (#14) merged.
