### ISSUE TITLE
Darwin panic: com.apple.rootless attr has no value

### ISSUE THREAD

**Issue by mmullis** [pkg/xattr#12]
xattr.Set causes panic on Darwin (16.5.0) when it encounters com.apple.rootless which is valueless. 
/bin is an example of this. 
```
$ xattr -l -x  /bin
com.apple.FinderInfo:
00000000  00 00 00 00 00 00 00 00 40 00 00 00 00 00 00 00  |........@.......|
00000010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
00000020
com.apple.rootless:
00000000
```

Panic:
```
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/pkg/xattr.Set(0xc4222bedc0, 0x1a, 0xc4222beb80, 0x12, 0x1954f70, 0x0, 0x0, 0x0, 0x0)
	src/github.com/pkg/xattr/xattr_darwin.go:50 +0x38d
```

Test case: 
`        err = Set(tmp.Name(), "com.apple.rootless", []byte{})
`

I'm not familiar enough with Go, the code or other requirements to propose a fix for this other than to just skip it when len is 0.

fyi: i hit this during a restore with restic.
thanks.

**Comment by kuba--** [comment]
@mmullis - I'll take a look.

**Comment by kuba--** [comment]
@mmullis - I've sent a pull request: https://github.com/pkg/xattr/pull/13
Please take a look if it works for you, `Set` will not crash for empty `data`.
On the other hand, on Darwin (OSX) you cannot set `com.apple.rootless xattr` (as far as I know it has to start with `user.` prefix. 
So `Set` function will return `com.apple.rootless: operation not permitted` error.

**Comment by kuba--** [comment]
Fix merged into the master branch
