### ISSUE TITLE
Solaris/Illumos Support

### ISSUE THREAD

**Issue by dave-fl** [pkg/xattr#15]
Would a PR be considered that added Illumos support?  It would require usage of cgo.

**Comment by kuba--** [comment]
@dave-fl - if adding `solaris` build tag (or any appropriate) to `_freebsd` file does not work and `cgo` is needed then I think it's fine (so far).
There are lot of things going on to support _illumos_ (https://github.com/golang/go/issues/20603).

**Comment by kuba--** [comment]
@dave-fl  - question: Are you working on support for *Illumos*?

**Comment by dave-fl** [comment]
I intended to but the owner of restic said a PR would not be accepted if it depedended on CGO. 

So I’ve opened 

https://github.com/golang/go/issues/24381

Once that is complete it can be worked on.

**Comment by kuba--** [comment]
@dave-fl - thanks for update. So maybe we can close it now (and reopen it when https://github.com/golang/go/issues/24381 will be fixed) - what do you think?

**Comment by kuba--** [comment]
I'm closing this issue because it depends on https://github.com/golang/go/issues/24381
We can re-open it later.
