### ISSUE TITLE
List() fails with ERANGE on SMB1

### ISSUE THREAD

**Issue by rawtaz** [pkg/xattr#16]
A [restic](https://restic.net) user recently reported [a problem](https://forum.restic.net/t/numerical-result-out-of-range/515) where reading of xattrs from a SMB1 mount point failed with an error "numerical result out of range", which is error 34, ERANGE.

Turns out that it works with SMB2, but for SMB1 the problem is probably due to what's summed up in https://github.com/xattr/xattr/issues/42, and the workaround is to make the buffer given to `syscall.Listxattrs()` one byte larger than the reported-to-be-needed size.

Would you be happy with a PR that changes `buf := make([]byte, size)` to `buf := make([]byte, size+1)` in `xattr_linux.go` (or just make the change yourself, that's fine by me!)?

Someone said they're going to take a look at it upstream, but a workaround here would probably be nice.

**Comment by kuba--** [comment]
@rawtaz - thanks for info. If you already have well tested and ready PR, 
I would be happy to merge it. Otherwise, I can play around a little bit a fix it.

**Comment by rawtaz** [comment]
I made the code change locally, but I don't have the means to try it in practice, so if you want to do that I'll let you have at it :) Thanks!

**Comment by kuba--** [comment]
@rawtaz - no worries. You can send PR and I'll try to test it out.
The most important is to be backward compatibile and not to break a build.

**Comment by rawtaz** [comment]
Biggest PR ever :)
