### ISSUE TITLE
Tests fail on tmpfs

### ISSUE THREAD

**Issue by rfjakob** [pkg/xattr#19]
This is on Fedora 27, where /tmp is a tmpfs mount:
```
$ df -Th /tmp
Filesystem     Type   Size  Used Avail Use% Mounted on
tmpfs          tmpfs  3.9G   12M  3.9G   1% /tmp
```
Tests fail because the Supported() check does not seem to work:
```
$ go test
--- FAIL: Test (0.00s)
	xattr_test.go:27: xattr.Set /tmp/572738598 user.test: operation not supported
--- FAIL: TestNoData (0.00s)
	xattr_test.go:77: xattr.Set /tmp/017916237 user.test: operation not supported
FAIL
exit status 1
FAIL	github.com/pkg/xattr	0.002s
```

**Comment by kuba--** [comment]
@rfjakob - thanks for testing!
Looks that for tests we have to check `syscall.ENOTSUP` error for all operations (`get`, `set`, `list`, ...). Replacing `listxattr` by `getxattr` may not solve the problem, because in your case tests failed for `Set` operation.

**Comment by rfjakob** [comment]
The problem with tmpfs is that it supports `security.*` attributes but not `user.*`.

This is why `Supported()` returns a false positive - the pull request fixes that.

**Comment by rfjakob** [comment]
(and if `Supported()` returns false, the tests will be skipped)

**Comment by kuba--** [comment]
I've just thought about something like this: https://github.com/pkg/xattr/pull/22
