### ISSUE TITLE
Symlink handling?

### ISSUE THREAD

**Issue by rfjakob** [pkg/xattr#28]
To be safe against symlink race attacks I propose to use the system call variants that do not follow symlinks for Get, Set and List. Even though they look different, all platforms have such a variant:

* `lgetxattr / lsetxattr / llistxattr` on Linux
* `SYS_EXTATTR_GET_LINK / SYS_EXTATTR_SET_LINK / SYS_EXTATTR_LIST_LINK` on FreeBSD
* `XATTR_NOFOLLOW` on Darwin

If you agree that this is a good idea I will send a PR. This will make having correct and safe xattr support in gocryptfs much easier.

**Comment by kuba--** [comment]
@rfjakob it's a good idea, but I instead of modifying current implementation we can extend API by _L_ functions (lgetxattr, llistxattr, lremovexattr and lsetxattr). So you can use either `xattr.Get(...)` or `xattr.LGet(...)`, etc. (also appropriate comments and/or README will be needed).

**Comment by rfjakob** [comment]
Ok!

**Comment by rfjakob** [comment]
Just a progress update, I'm almost there but have found unrelated [Travis problems](https://travis-ci.org/pkg/xattr/jobs/376069383#L471). The PR will include an attempt to fix these.

Also, Darwin xattr support [just landed](https://github.com/golang/sys/commit/0b6bef996066e7afc14080cbafc9719ca35f6204) in x/sys/unix, so I'll refactor to use it.

**Comment by rfjakob** [comment]
PR created at https://github.com/pkg/xattr/pull/29
