### ISSUE TITLE
github build action

### ISSUE THREAD

**Issue by kuba--** [pkg/xattr#41]
@fd0 @rfjakob @harshavardhana - question:
What do you think (for this project) about replacing travis build by github action?
How many go versions do we want to support?

**Comment by harshavardhana** [comment]
From mc point of view we only care about go1.13 and above. 

@fd0 might have more requirements.

**Comment by fd0** [comment]
For restic, I'm trying to support Go >= 1.11 (because that's what Debian stable and oldstable have). I'll also convert the restic repo to GitHub actions.
