### ISSUE TITLE
Code is not formatted according to gofmt?

### ISSUE THREAD

**Issue by fd0** [pkg/xattr#5]
Hi,

first, thanks a lot for tagging a release! I appreciate that a lot!

I noticed that the code is not formatted with `gofmt`, and you've removed the call to `goimports` (which checks for that) from the Travis tests. Was that intentional? Will you accept a small PR from me which adds it back?

Thanks!

**Comment by kuba--** [comment]
@fd0  - my bad (I removed that line when simplifying build file) - let me quickly fix it.

**Comment by kuba--** [comment]
fixed
