### ISSUE TITLE
Build is broken on linux with the recent changes

### ISSUE THREAD

**Issue by bwang221** [pkg/xattr#51]
https://github.com/pkg/xattr/commit/994316708194a4ca6198b54c879dc5881ca59c71

src/github.com/pkg/xattr/xattr_linux.go:34:7: undefined: errors.Is

**Comment by kuba--** [comment]
What version of go, you're using?
Based on CI, it should work fine on go.14.x and go.15.x.

**Comment by brianauxiit** [comment]
You are right, the Go is a bit too old, 1.9.x.
