### ISSUE TITLE
Superfluous space in `(*Error).String()` when `Error.Name == ""`

### ISSUE THREAD

**Issue by jfrech** [pkg/xattr#58]
I would like for
https://github.com/pkg/xattr/blob/38c1411ffffe19e215a445909527a083dca8dc7f/xattr.go#L32-L34
to get changed to
```
func (e *Error) Error() string {
    if e.Name != "" {
        return e.Op + " " + e.Path + " " + e.Name + ": " + e.Err.Error()
    } else {
        return e.Op + " " + e.Path + ": " + e.Err.Error()
    }
}
```
since I do not want the superfluous space returned from `xattr.go`'s `list`'s errors in my log files:
https://github.com/pkg/xattr/blob/38c1411ffffe19e215a445909527a083dca8dc7f/xattr.go#L206-L225

**Comment by kuba--** [comment]
@jfrech - PTAL https://github.com/pkg/xattr/pull/59
does it work for you (it's more generic)
