### ISSUE TITLE
API stutters a lot

### ISSUE THREAD

**Issue by fd0** [pkg/xattr#6]
Hi,

while using the `xattr` package I noticed that the API stutters a lot, e.g. the `XAttrError` type needs to be referred to from external code as `xattr.XAttrError`. It would be much nicer to rename it to `Error`, so that the referral would look like `xattr.Error` instead. It's the same with the functions, `xattr.Get()` instead of `xattr.Getxattr()` would reduce the stutter a lot.

Are you interested in a PR which fixes this? If not, please feel free to close this issue (and I'm going to live with the stutter ;).

**Comment by kuba--** [comment]
sounds good to me - send PR.

**Comment by fd0** [comment]
Thanks!
