### ISSUE TITLE
EINVAL instead of ENOTSUP on Solaris

### ISSUE THREAD

**Issue by greatroar** [pkg/xattr#67]
On Linux and Darwin at least, xattr.List returns ENOTSUP when the operation is not supported on a file. On Solaris, the [openat](https://illumos.org/man/2/openat) call fails with EINVAL for the O_XATTR flag. This presumably applies to all operations, but in restic/restic#3839 we have a failure from List specifically.

We could fix this in restic, but since pkg/xattr already tries to simulate the Linux/BSD interface on Solaris, maybe this library could change the EINVAL to ENOTSUP and make porting to Solaris easier for everyone?

**Comment by kuba--** [comment]
@greatroar - PTAL if this quick fix (https://github.com/pkg/xattr/pull/68) works for you on solaris.

**Comment by kuba--** [comment]
@greatroar - ☝🏻
